In [4]:
import numpy as np
AboAhmad=np.load("Abo Ahmad.npy")
Baghdad=np.load("Baghdad.npy")
Bravo= np.load( "Bravo.npy"  )
Gardens=np.load("Gardens.npy")
Karaz=np.load("Karaz.npy")
Mawares=np.load("Mawares.npy")
Maxmar=np.load("Max mar.npy")
Shini=np.load("Shini.npy")
prices=[AboAhmad,Baghdad,Bravo,Gardens,Karaz,Mawares,Maxmar,Shini]
prices = np.array(prices)
print (prices)
amounts = np.array([2, 1.5, 3, 6, 1, 1, 2, 3])
total_costs = np.dot(amounts, prices)
print (total_costs)
min_cost = np.argmin(total_costs)
print("Chosen grocery:", min_cost)


[[ 2.   2.   3.3  1.5  8.   2.5  7.   3.3]
 [ 3.1  3.   3.5  3.   8.   5.  10.   5. ]
 [ 3.   3.   3.3  1.5  8.   3.   9.   3. ]
 [ 4.   2.4  3.5  3.  10.   5.  12.   5. ]
 [ 3.   2.5  4.   1.5  8.   3.   7.   4. ]
 [ 2.3  2.   3.3  1.  12.   3.   7.   3.3]
 [ 3.5  3.   5.   3.  12.   5.  13.   4. ]
 [ 2.7  2.   3.   2.   7.   2.   8.   3.5]]
[ 62.05  48.4   69.05  44.5  177.    73.5  192.    78.9 ]
Chosen grocery: 3
